-- Generated by bundler-hs
{- ORMOLU_DISABLE -}
{-# OPTIONS_GHC -Wno-unused-imports -Wno-unused-top-binds #-}
{- a block comment
   spanning lines -}
{- ORMOLU_ENABLE -}
{-# LANGUAGE LambdaCase #-}
module Main (main) where

import qualified Alg

main :: IO ()
main = print (Alg.inc 1)
