-- | The names the implicit Prelude import brings into unqualified scope.
--
-- Generated from @ghc -e ':browse Prelude'@ (base 4.20). Operators are left
-- out on purpose: an operator can never take a suffix, so the bundler cannot
-- move a library one out of Prelude's way anyway, and listing them here would
-- only turn bundles that work today into errors.
module Bundler.PreludeNames
  ( preludeNames,
  )
where

import Bundler.Symbols (NsKey (..), OccKey)
import Data.Set (Set)
import Data.Set qualified as Set

-- | Every alphanumeric name Prelude exports, in its namespace bucket. A
-- library name that keeps its original spelling in the bundle must avoid
-- these: a top-level definition does not shadow the implicit Prelude import,
-- it makes every use of the name ambiguous.
preludeNames :: Set OccKey
preludeNames =
  Set.fromList $
    [(NsValue, n) | n <- values]
      <> [(NsTcCls, n) | n <- typesAndClasses]
      <> [(NsData, n) | n <- dataConstructors]
  where
    values :: [String]
    values =
      [ "abs",
        "acos",
        "acosh",
        "all",
        "and",
        "any",
        "appendFile",
        "asTypeOf",
        "asin",
        "asinh",
        "atan",
        "atan2",
        "atanh",
        "break",
        "ceiling",
        "compare",
        "concat",
        "concatMap",
        "const",
        "cos",
        "cosh",
        "curry",
        "cycle",
        "decodeFloat",
        "div",
        "divMod",
        "drop",
        "dropWhile",
        "either",
        "elem",
        "encodeFloat",
        "enumFrom",
        "enumFromThen",
        "enumFromThenTo",
        "enumFromTo",
        "error",
        "errorWithoutStackTrace",
        "even",
        "exp",
        "exponent",
        "fail",
        "filter",
        "flip",
        "floatDigits",
        "floatRadix",
        "floatRange",
        "floor",
        "fmap",
        "foldMap",
        "foldl",
        "foldl'",
        "foldl1",
        "foldr",
        "foldr1",
        "fromEnum",
        "fromInteger",
        "fromIntegral",
        "fromRational",
        "fst",
        "gcd",
        "getChar",
        "getContents",
        "getLine",
        "head",
        "id",
        "init",
        "interact",
        "ioError",
        "isDenormalized",
        "isIEEE",
        "isInfinite",
        "isNaN",
        "isNegativeZero",
        "iterate",
        "last",
        "lcm",
        "length",
        "lex",
        "liftA2",
        "lines",
        "log",
        "logBase",
        "lookup",
        "map",
        "mapM",
        "mapM_",
        "mappend",
        "max",
        "maxBound",
        "maximum",
        "maybe",
        "mconcat",
        "mempty",
        "min",
        "minBound",
        "minimum",
        "mod",
        "negate",
        "not",
        "notElem",
        "null",
        "odd",
        "or",
        "otherwise",
        "pi",
        "pred",
        "print",
        "product",
        "properFraction",
        "pure",
        "putChar",
        "putStr",
        "putStrLn",
        "quot",
        "quotRem",
        "read",
        "readFile",
        "readIO",
        "readList",
        "readLn",
        "readParen",
        "reads",
        "readsPrec",
        "realToFrac",
        "recip",
        "rem",
        "repeat",
        "replicate",
        "return",
        "reverse",
        "round",
        "scaleFloat",
        "scanl",
        "scanl1",
        "scanr",
        "scanr1",
        "seq",
        "sequence",
        "sequenceA",
        "sequence_",
        "show",
        "showChar",
        "showList",
        "showParen",
        "showString",
        "shows",
        "showsPrec",
        "significand",
        "signum",
        "sin",
        "sinh",
        "snd",
        "span",
        "splitAt",
        "sqrt",
        "subtract",
        "succ",
        "sum",
        "tail",
        "take",
        "takeWhile",
        "tan",
        "tanh",
        "toEnum",
        "toInteger",
        "toRational",
        "traverse",
        "truncate",
        "uncurry",
        "undefined",
        "unlines",
        "until",
        "unwords",
        "unzip",
        "unzip3",
        "userError",
        "words",
        "writeFile",
        "zip",
        "zip3",
        "zipWith",
        "zipWith3"
      ]

    typesAndClasses :: [String]
    typesAndClasses =
      [ "Applicative",
        "Bool",
        "Bounded",
        "Char",
        "Double",
        "Either",
        "Enum",
        "Eq",
        "FilePath",
        "Float",
        "Floating",
        "Foldable",
        "Fractional",
        "Functor",
        "IO",
        "IOError",
        "Int",
        "Integer",
        "Integral",
        "Maybe",
        "Monad",
        "MonadFail",
        "Monoid",
        "Num",
        "Ord",
        "Ordering",
        "Rational",
        "Read",
        "ReadS",
        "Real",
        "RealFloat",
        "RealFrac",
        "Semigroup",
        "Show",
        "ShowS",
        "String",
        "Traversable",
        "Word"
      ]

    dataConstructors :: [String]
    dataConstructors =
      [ "EQ",
        "False",
        "GT",
        "Just",
        "LT",
        "Left",
        "Nothing",
        "Right",
        "True"
      ]
